name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build with Gradle
      run: |
        cd grocery
        ls
        chmod +x gradlew
        ./gradlew build
        ./gradlew assembleDebug
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CMD_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      run: |
          #cd grocery
          ls
      #id: upload-release-asset 
      #uses: actions/upload-release-asset@v1
      #env:
        #GITHUB_TOKEN: ${{ secrets.CMD_TOKEN }}
      #with:
        #upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        #asset_path: ./app/build/outputs/apk/debug/app-debug.apk
        #asset_name: app-debug.apk
        #asset_content_type: application/zip
